# Generated by Django 3.0.6 on 2020-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorname', models.CharField(max_length=50, null=True)),
                ('creationdate', models.DateField(auto_now_add=True, null=True)),
                ('notetext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LittleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorname', models.CharField(max_length=50, null=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('notetext', models.CharField(max_length=210, null=True)),
                ('notifydate', models.DateTimeField()),
            ],
        ),
    ]
