# Generated by Django 3.0.6 on 2020-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0004_reverse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reverse',
        ),
        migrations.AddField(
            model_name='profile',
            name='oldmail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
