# Generated by Django 3.0.6 on 2020-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0007_auto_20201018_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littlenote',
            name='notifydate',
            field=models.DateTimeField(null=True),
        ),
    ]
