# Generated by Django 3.0.6 on 2020-11-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0008_auto_20201020_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorname', models.CharField(max_length=50, null=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('eventdate', models.DateTimeField()),
                ('notetext', models.CharField(max_length=210, null=True)),
                ('eventtype', models.CharField(max_length=50, null=True)),
                ('eventimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
