# Generated by Django 3.0.6 on 2020-11-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0013_auto_20201105_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorname', models.CharField(max_length=50, null=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('mooddate', models.DateTimeField()),
                ('notetext', models.CharField(max_length=210, null=True)),
                ('eventtype', models.CharField(max_length=50, null=True)),
                ('moodtype', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
