# Generated by Django 3.0.6 on 2021-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0015_eventnote_isaddphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorname', models.CharField(max_length=50, null=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
                ('score', models.FloatField()),
            ],
        ),
    ]
