# Generated by Django 3.0.6 on 2021-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0016_surveyresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodnote',
            name='moodtype',
            field=models.IntegerField(null=True),
        ),
    ]
